name: rnamining
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.14.6
  - pip=26.1.2
  - setuptools=83.0.0
  - numpy=2.5.1
  - pandas=3.0.3
  - scipy=1.18.0
  - scikit-learn=1.9.0
  - xgboost=3.3.0=cpu*
  - py-xgboost=3.3.0=cpu*
  - libxgboost=3.3.0=cpu*
  - biopython=1.87
  - pytest=9.0.3
  - ipykernel=7.3.0
  - jupyterlab=4.6.2
